name: CI

on:
  push:
    branches: [main, feature/branch]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: echo hello, world!

      - name: running a custom script here
        run: |
          ls -al

      - name: Run a multi-line script
        run:
          echo Add other actions to build,
          echo test, and deploy your project

      - name: Run amulti-line script
        run: |
          echo add other actions to build
      - name: maven build
        run: mvn generate-test-sources

      - name: docker build
        run: docker build . -t demo-java2.0

